name: Vista
description: "vista."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.5+23

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_links: ^6.4.0
  audio_waveforms: ^1.3.0
  aws_s3_api: ^2.0.0
  badges: ^3.1.2
  build_runner: ^2.4.15
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.4.1
  clipboard: ^0.1.3
  confetti: ^0.7.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  dotted_border: ^2.1.0
  emoji_picker_flutter: ^4.3.0
  equatable: ^2.0.7
  exif: ^3.3.0
  file_picker: ^9.1.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.4.1
  flutter_drawing_board: ^0.9.5
  flutter_emoji: ^2.5.1
  flutter_exif_rotation: ^0.5.2
  flutter_image_compress: ^2.4.0
  flutter_instagram_storyboard: ^1.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.1.0
  flutter_mentions: ^2.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  image: ^4.5.3
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  persian_datetime_picker: ^3.1.0
  photo_view: ^0.15.0
  pro_image_editor: ^9.0.2
  shamsi_date: ^1.0.4
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  story_designer: ^2.1.0
  supabase_flutter: ^2.8.4
  timeago: ^3.7.0
  timeline_tile: ^2.0.0
  timelines_plus: ^1.0.6
  url_launcher: ^6.3.1
  video_compress: ^3.1.4
  video_player: ^2.8.1
  visibility_detector: ^0.4.0+2
  voice_message_package: ^2.2.1
  video_trimmer: ^5.0.0
  drift: ^2.16.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.0
dependency_overrides:
  intl: ^0.19.0


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/view/util/images/vistalogo-new.png"
  adaptive_icon_background: "#000000" # رنگ پس‌زمینه برای اندروید
  adaptive_icon_foreground: "lib/view/util/images/vistalogo-new.png" # آیکون جلو برای اندروید
  min_sdk_android: 19
  web:
    generate: true
    image_path: "lib/view/util/images/vistalogo-new.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "lib/view/util/images/vistalogo-new.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/view/util/images/vistalogo-new.png"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/view/util/images/vistalogo.png
    - lib/view/util/images/vistalogo-new.png
    - lib/view/util/images/headerBack.jpg
    - lib/view/util/images/default-avatar.jpg
    - lib/view/util/images/fish.svg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: lib/view/util/fonts/Vazir.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Bauhaus
      fonts:
        - asset: lib/view/util/fonts/BauhausBold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
