org.gradle.jvmargs=-Xmx4096m -Xms1024m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx2048m
android.useAndroidX=true
android.enableJetifier=true
# org.gradle.java.home=D:/Program Files/Java/jdk-171
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
org.gradle.parallel=true
org.gradle.caching=true
android.enableR8.fullMode=false

# Disable Kotlin incremental compilation to fix build issues
kotlin.incremental=false

# Performance optimizations
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.workers.max=4
android.enableD8.desugaring=true
android.enableR8=true

# AWS Configuration for production builds
AWS_ACCESS_KEY_ID=4f4716fb-fa84-4ae7-9c8b-34d2a0896cdf
AWS_SECRET_ACCESS_KEY=a6b4db27b4c54bfa46cbc4fd8a4ba2079e2da0cd2800acdc80dd758f8b2c1ec5
AWS_REGION=ir-thr-at1
AWS_ENDPOINT_URL=https://coffevista.s3.ir-thr-at1.arvanstorage.ir
AWS_BUCKET_NAME=coffevista
